.ALIASES
C_C1            C1(1=0 2=N01199 )
C_C2            C2(1=0 2=N01199 )
R_R6            R6(1=0 2=N00865 )
V_V1            V1(+=N01199 -=0 )
C_C3            C3(1=0 2=OUT )
R_R5            R5(1=N00865 2=OUT )
R_R66           R66(1=0 2=N00865 )
C_1n            1n(1=0 2=OUT )
R_R4            R4(1=N00325 2=OUT )
X_U4            U4(IN=N01199 OUT=N00325 GND=N00865 )
_    _(OUT=OUT)
.ENDALIASES
