.ALIASES
X_U1            U1(+=N00994 -=N00288 V+=N00862 V-=N00795 OUT=OUT )
V_V3            V3(+=N00862 -=0 )
R_R1            R1(1=IN 2=N00261 )
R_R6            R6(1=0 2=N00261 )
R_R5            R5(1=0 2=N00994 )
V_V1            V1(+=IN -=0 )
R_R3            R3(1=OUT 2=N00288 )
C_C2            C2(1=N00261 2=N00288 )
C_C4            C4(1=N00261 2=OUT )
V_V2            V2(+=0 -=N00795 )
_    _(out=OUT)
_    _(in=IN)
.ENDALIASES
